[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/6788290?u=d9a388224b87d55106cb3e6199d02ebc1d8e0553&v=4\""
    alt="Avatar of Brigitta Sipőcz"
>}}
Brigitta Sipőcz'''
link = 'https://github.com/bsipocz'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/335567?v=4\""
    alt="Avatar of M Bussonnier"
>}}
M Bussonnier'''
link = 'https://github.com/Carreau'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/60778417?u=6272842e4c0946308604a5f54cdaa8e6505adcbe&v=4\""
    alt="Avatar of Jake Bowhay"
>}}
Jake Bowhay'''
link = 'https://github.com/j-bowhay'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/123428?v=4\""
    alt="Avatar of Jarrod Millman"
>}}
Jarrod Millman'''
link = 'https://github.com/jarrodmillman'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/20140352?u=fa6debadd435c15847d1435c49753f349e2d3526&v=4\""
    alt="Avatar of Lars Grüter"
>}}
Lars Grüter'''
link = 'https://github.com/lagru'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/2365790?v=4\""
    alt="Avatar of Eric Larson"
>}}
Eric Larson'''
link = 'https://github.com/larsoner'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image
    src="https://avatars.githubusercontent.com/u/5142394?u=310e7999b329801a47ebc999c2243fc9f2b32434&v=4\""
    alt="Avatar of Matthew Feickert"
>}}
Matthew Feickert'''
link = 'https://github.com/matthewfeickert'
